### ISSUE TITLE
Use `channelGroup` to determine the config group used for the channel

### ISSUE THREAD

**Issue by ianhi** [tlambert03/napari-micromanager#26]
There is `core.getChannelGroup` which should be used instead of hardcoding `"Channel"` https://github.com/tlambert03/napari-micromanager/blob/57ee6672aad52e171058376f2a115305f2dabc84/micromanager_gui/main_window.py#L237-L239

However, we should keep the hardcoded `Channel` as a fallback because it's not clear if it's even possible to set this via a config file (and micromanager doesn't seem to save it into the config) see https://forum.image.sc/t/how-to-set-channelgroup-in-config-file/55746

**Comment by tlambert03** [comment]
agreed!
