### ISSUE TITLE
Development tips?

### ISSUE THREAD

**Issue by ianhi** [tlambert03/napari-micromanager#27]
Any tips+tricks for developing a napari plugin? In particular is there an easy way to start up napari and immediately load the plugin? Every time I want to test something I am opening napari from the terminal, loading the plugin and then loading the demo config.

**Comment by tlambert03** [comment]
> In particular is there an easy way to start up napari and immediately load the plugin?

**Comment by tlambert03** [comment]
and here's a script for adding a plugin dock widget to an existing viewer via a script:

```py
import napari


v = napari.Viewer()
dw, main_window = v.window.add_plugin_dock_widget('micromanager')

core = main_window._mmc
core.loadSystemConfiguration('demo')

napari.run()
```
