### ISSUE TITLE
add to pypi

### ISSUE THREAD

**Issue by ianhi** [tlambert03/napari-micromanager#32]
Now that I'm trying to use this on micrscopes it would be nice to be able to pip install specific versions.

**Comment by tlambert03** [comment]
have you tried `pip install git+https://github.com/tlambert03/napari-micromanager.git@<commit>`

**Comment by tlambert03** [comment]
I added a release candidate to pypi: https://pypi.org/project/napari-micromanager/
we can version things and update their... might stick with release candidate versions until certain things are more stable  (particularly things like #33)

**Comment by ianhi** [comment]
makes sense to me - thanks!
