### ISSUE TITLE
`_on_system_configuration_loaded` should not modify system state

### ISSUE THREAD

**Issue by ianhi** [tlambert03/napari-micromanager#33]
Noticed today that when I opened napari-micromanager (manually called `_on_system_configuration_loaded` because it was already loaded remotely) that the objective position changed from where it already was. This seems to be because the objective_combobox was populated with a list default order but didn't check the current state of the objectives so it ended up calling `change_objective`.

I have two proposed improvements:

1. [ ] At the end of `init` the system state should be queried  to account for the config already being loaded
2. [ ] `refresh_objective` and friends should take care to not accidentally change the current state via the callbacks on their widgets.

**Comment by tlambert03** [comment]
definitely anything you want to submit that protects potential damage is very welcome and high priority
