### ISSUE TITLE
More thoughts/questions on project scope

### ISSUE THREAD

**Issue by ianhi** [tlambert03/napari-micromanager#45]
I think that the way this library special cases the single body, multi axis, single camera microscope is part of what makes the UI very easy to use.  While this gives real gains in terms of the UI just magically working, it is also limiting for other cases. If the hope is to one day support other styles of microscope or greater generality then are there design decisions that should be made now that will make that easier in the future? Or is that perhaps not the hope?

(It's that special casing this style of setup vs others is the `scope` that I was trying to grapple with in https://github.com/tlambert03/napari-micromanager/pull/40#issuecomment-910864118.)

**Comment by tlambert03** [comment]
> If the hope is to one day support other styles of microscope or greater generality then are there design decisions that should be made now that will make that easier in the future? Or is that perhaps not the hope?

More or less the same answer as https://github.com/tlambert03/napari-micromanager/pull/40#issuecomment-910866966:

I don't have any particular "upper bound" in mind in terms of what could/should be supported here.  The hope is to generally make the pymmcore API accessible/usable from within napari (or, more generally, for pymmcore-plus, within a python GUI event loop, implemented in any front-end).

This challenge of making common use cases just magically work, while also supported arbitrarily complex use cases is just universally difficult.  So we start with some common use cases, make them work, then step back and look at the patterns we've adopted and see if we can generalize them more... then iterate. 

> design decisions that should be made now that will make that easier in the future

I'm sure there are, and I'm always open to them!  So I guess the general answer here is that "this project is open to any idea that can make the package useful to a broader group of users, while still having at least one 'mode' that makes the most common use cases easy"
